spring:
  application:
    name: echolink
    jwt:
      secret: ${JWT_SECRET:5mKbY6qNfK7dYjz9WvTn3GpLr4XsQe8BcDfGhJkLmNpQrStUvWxYz123456789AB}
      expiration: 3600000

  datasource:
    url: ${DB_JDBC_URL:jdbc:mariadb://localhost:13306/echolink}
    username: ${DB_USERNAME:echolink}
    password: ${DB_PASSWORD:echolink}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true

  flyway:
    enabled: true

  geo-api:
    base-url: https://geo.api.gouv.fr
  open-meteo:
    weather:
      base-url: https://api.open-meteo.com/v1
    air-quality:
      base-url: https://air-quality-api.open-meteo.com/v1/

  startup-initializer:
    enabled: true
