spring:
  application:
    name: echolink
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:mariadb://localhost:13306/echolink
    username: echolink
    password: echolink
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
  flyway:
    enabled: true
  startup-initializer:
    enabled: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:dumb_5mKbY6qNfK7dYjz9WvTn3GpLr4XsQe8BcDfGhJkLmNpQrStUvWxYz123456789AB}
      expiration: 3600000
  integrations:
    geo-api:
      base-url: https://geo.api.gouv.fr
    open-meteo:
      weather:
        base-url: https://api.open-meteo.com/v1
      air-quality:
        base-url: https://air-quality-api.open-meteo.com/v1/
